### ISSUE TITLE
Replace numpad comma with dot

### ISSUE THREAD

**Issue by oliversalzburg** [RAnders00/kbd-german-eliminate-dead-keys#1]
I've been running a similarly modified keymap for years. However, I also have the `,` on the numpad replaced with a `.`. 

This allows for easier input of IPv4 addresses and is generally more useful while writing code, as decimals are usually separated with `.`, not `,`.

Excel will still work as expected, even in German. However, some German applications don't like it when you enter decimals with a `.` and they will complain about invalid number input. For me, the benefits outweigh this issue though.

**Comment by xelra** [comment]
I always thought that the `,` or `.` on the numpad are neither of those keys. They are whatever you set for number format in your locale.

**Comment by oliversalzburg** [comment]
@xelra That is, if anything, application-dependent. Regardless, I usually work in en-US, but the key still produces `,`. And if it *was* locale-dependent, then it would be one more reason to adjust the keymap to always produce the same results.

**Comment by RAnders00** [comment]
For me, this is a non-issue. Feel free to post more arguments why the `,` on the numpad should be changed to a `.` on a **German** keyboard layout, I will happily read and consider them, but for now I simply do not see the point. If you are looking for an English keyboard layout without dead keys, that would have to be done as a separate keyboard layout (if you want, you can submit a pull request creating the file `english.klc` - that could then contain an English layout)
