### ISSUE TITLE
How to set it up?

### ISSUE THREAD

**Issue by xeruf** [RAnders00/kbd-german-eliminate-dead-keys#2]
I have installed it on my Windows machine, selected the layout, but nothing changed. Did I miss something? Do I have to restart?

**Comment by xelra** [comment]
Are you sure you selected it? What exactly is the change you're expecting?

**Comment by xeruf** [comment]
Yes, I selected it. 

I expect keys such as ` and ^ to appear immediately upon typing, but they still only appear  after tapping them twice.

**Comment by Anthrazz** [comment]
After the installation must you still manually select the keyboard layout in your Windows settings.

The settings can be found in the control panel under `Time and Language` -> `Language` on the left menu -> Select at your bottom your language and click on `Options`. Then you can remove the other Keyboard Layouts at the bottom.
